trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macOS-10.14'
    windows:
      imageName: 'windows-2019'
  maxParallel: 10

pool:
  vmImage: $(imageName)

steps:
- script: cargo +stable fmt -- --check
- script: cargo check-core

- script: cargo test-core
- script: cargo bench-core

- script: cargo docs-core
- publish: target/doc
  artifact: documentation
