strategy:
  matrix:
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- script: cargo check-core

- script: cargo test-core
- script: cargo bench-core

- script: cargo docs-core
- publish: target/doc
  artifact: documentation
