trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macOS-10.14'
    windows:
      imageName: 'windows-2019'
  maxParallel: 10

pool:
  vmImage: $(imageName)

steps:
- script: rustup component add clippy rustfmt
- script: cargo fmt -- --check
- script: cargo check-core
- script: cargo clippy-core
- script: cargo docs-core
- script: cargo test-core
- script: cargo bench-core
