[package]
name = "moxie"
version = "0.1.0"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Declarative, asynchronous, incremental UI component runtime."

[dependencies]
moxie-core = { path = "moxie-core" }

[workspace]
members = [
    "mox",
    "moxie-core",
    # "moxie-dom",
    # "moxie-dom/examples/hacking/crate",
    "topo",
    "topo/macro",
    # "moxie-wrench",
]
