[package]
name = "moxie"
version = "0.1.0"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Declarative, asynchronous, incremental UI component runtime."

[dependencies]
futures-preview = { version = "0.3.0-alpha.16", features = [ "async-await", "nightly" ] }
parking_lot = "0.8"
topo = { path = "topo", version = "0.8" }

[workspace]
members = [
    "dom",
    "dom/examples/hacking",
    "topo",
    "topo/macro",
]
