[package]
name = "moxie"
version = "0.1.0"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Declarative, asynchronous, incremental UI component runtime."

[dependencies]
futures-preview = "0.3.0-alpha.18"
parking_lot = "0.9"
scopeguard = "1"
tracing = "^0.1"
topo = { path = "topo", version = "0.8" }

[workspace]
members = [
    "dom",
    "dom/examples/hacking",
    "dom/examples/todo",
    "topo",
    "topo/macro",
]

[features]
default = ["log"]
log = ["tracing/log"]
