[package]
name = "moxie"
version = "0.1.0"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Experimental UI component library."

[dependencies]
generational-arena = "0.1"
mox-macro = { path = "mox-macro" }
proc-macro-hack = "0.5"
salsa = "0.8"

[profile.dev]
opt-level = 1

[workspace]
members = [
    "mox",
    "mox-macro/",
    # "moxie-web/crate/",
    "moxie-wrench",
]
