[package]
name = "moxie"
version = "0.1.0"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Experimental UI component library."

[dependencies]
mox-macro = { path = "mox-macro" }
proc-macro-hack = "0.5"

[workspace]
members = [
    "mox-macro/",
    "moxie-web/crate/",
]
