[package]
name = "only"
version = "0.1.0"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "Apache 2.0/MIT"
description = "Experimental UI component library."

[workspace]
members = [
    "only-web/crate/",
]
