[package]
name = "moxie"
version = "0.1.0"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Declarative, asynchronous, incremental UI component runtime."

[dependencies]
chashmap = "2"
downcast-rs = "1"
froggy = "0.4"
futures-preview = { version = "0.3.0-alpha.15", features = [ "async-await", "nightly" ] }
fxhash = "0.2"
mox = { path = "mox" }
moxie-core = { path = "moxie-core" }
parking_lot = "0.7"
rental = "0.5"
shrinkwraprs = "0.2"
tokio-trace = { version = "0.1", features = ["log"], optional = true }
typename = "0.1"

[features]
default = [ "instrument" ]
instrument = [ "tokio-trace" ]

[workspace]
members = [
    "mox",
    "moxie-core",
    # "moxie-dom",
    # "moxie-dom/examples/hacking/crate",
    "topo",
    "topo/macro",
    # "moxie-wrench",
]
