[package]
name = "moxie"
version = "0.1.0"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Declarative, asynchronous, incremental UI component runtime."

[dependencies]
chashmap = "2"
futures-preview = "0.3.0-alpha.13"
fxhash = "0.2"
log = "0.4"
mox = { path = "mox" }
parking_lot = "0.7"
rental = "0.5"

[workspace]
members = [
    "mox",
    "moxie-wrench",
]
