[package]
name = "dom-hacking"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0/MIT"

[dependencies]
log = "0.4"
moxie = { path = "../../../" }
moxie-dom = { path = "../../" }
stdweb = "0.4.16"
typed-html = { version = "0.2", features = ["stdweb"] }
web_logger = "0.1"
