[package]
name = "mox"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
gll = "0.0.2"
gll-macros = "0.0.2"
Inflector = "0.11"
proc-macro2 = "0.4.20"
quote = "0.6"
syn = { version = "0.15", features = ["full", "visit-mut"] }
