[package]
name = "moxie-dom"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "TBA"

[dependencies]
futures-preview = "0.3.0-alpha.17"
moxie = { path = "../", version = "0.1" }
stdweb = "0.4.16"
tracing = { version = "0.1.1", features = ["log"] }
