[package]
name = "moxie-dom"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "TBA"

[dependencies]
derive_builder = "0.7"
futures-preview = "0.3.0-alpha.17"
moxie = { path = "../", version = "0.1" }
scopeguard = "1"
tracing = { version = "0.1.1", features = ["log"] }
wasm-bindgen = "0.2.48"

[dependencies.web-sys]
version = "0.3.25"
features = [
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "HtmlButtonElement",
    "HtmlElement",
    "MouseEvent",
    "Node",
    "Text",
    "Window",
]
