[package]
name = "moxie-dom"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "TBA"

[dependencies]
moxie = { path = "../", version = "0.1" }
stdweb = "0.4.16"
tokio-trace = { version = "0.1", features = ["log"] }
topo = { version = "0.8.0", path = "../topo" }
