[package]
name = "topo"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"

[dependencies]
owning_ref = "0.4"
scopeguard = "1"
topo-macro = { path = "macro" }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "simple"
harness = false
