[package]
name = "topo"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"

[dependencies]
im-rc = "13"
owning_ref = "0.4"
tokio-trace = { version = "0.1", features = ["log"] }
topo-macro = { path = "macro" }
