[package]
name = "topo"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"

[dependencies]
im = "13"
owning_ref = "0.4"
static_assertions = "0.3"
topo-macro = { path = "macro" }
