on: push
jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - run: cargo test-core

  dom:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo check-dom-lib
    - run: cargo build-dom-hacking
    - run: cargo build-dom-todo
    - uses: actions/upload-artifact@master
      with:
        name: dom-examples
        path: dom/examples

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add rustfmt
    - run: cargo fmt -- --check
    - run: cargo fmt-ofl -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add clippy
    - run: cargo clippy-core
    - run: cargo clippy-dom

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cargo docs-all
    - run: cargo docs-ofl
    - uses: actions/upload-artifact@master
      with:
        name: docs
        path: target/doc

  website:
    needs: [core, dom, fmt, clippy, docs]
    runs-on: ubuntu-latest
    steps:

    # get the code and the output of examples and docs
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: dom-examples
        path: dom/examples
    - uses: actions/download-artifact@master
      with:
        name: docs
        path: target/doc

    # clone the website branch into a separate folder, clean it for build output
    - uses: actions/checkout@gh-pages
      path: ../website
    - working-directory: ../website
      # https://stackoverflow.com/questions/22339837/linux-command-to-delete-all-files-except-git-folder
      run: |
        git rm -rf .
        git clean -fxd

    # build it
    - run: cargo ofl website build ../website

    # publish it if we're on master
    - if: github.ref == 'ref/heads/master'
      working-directory: ../website
      run: |
        git add -a
        git commit -m $GITHUB_SHA
        git push origin gh-pages

  published:
    needs: [website]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: echo ${{ github.ref }}
    - if: github.ref == 'ref/heads/master'
      run: |
        cargo login ${{ secrets.CARGO_API_TOKEN }}
        cargo ofl published
