on: push
jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@master
    - run: cargo test-core

  dom:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@master
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo check-dom-lib
    - run: cargo build-dom-hacking
    - run: cargo build-dom-todo

  housekeeping:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add rustfmt clippy
    - run: cargo fmt -- --check
    - run: cargo fmt-scripts-check
    - run: cargo clippy-core
    - run: cargo clippy-dom
    - run: cargo docs-all

  published:
    needs: [core, dom, housekeeping]
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    - run: cargo login ${{ secrets.CARGO_API_TOKEN }}
    - run: cargo published
