on: push
jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@master
    - run: cargo test-core

  dom:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@master
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo check-dom-lib
    - run: cargo build-dom-hacking
    - run: cargo build-dom-todo
  
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add rustfmt
    - run: cargo fmt -- --check
    - run: cargo fmt-scripts-check
  
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add clippy
    - run: cargo clippy-core
    - run: cargo clippy-dom
  
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cargo docs-all
    - run: cargo docs-tools

  can_release:
    needs: [core, dom, fmt, clippy, docs]
    uses: actions/bin/filter@master
    args: branch master

  published:
    needs: can_release
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    - run: cargo login ${{ secrets.CARGO_API_TOKEN }}
    - run: cargo published