on: push
jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - run: cargo test-core

  dom:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo check-dom-lib
    - run: cargo build-dom-hacking
    - run: cargo build-dom-todo
    - uses: actions/upload-artifact@master
      with:
        name: dom-examples
        path: dom/examples

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add rustfmt
    - run: cargo fmt -- --check
    # FIXME https://github.com/anp/moxie/issues/27
    # - run: cargo fmt-ofl -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add clippy
    - run: cargo clippy-core
    - run: cargo clippy-dom

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cargo docs-all
    - run: cargo docs-ofl
    - uses: actions/upload-artifact@master
      with:
        name: docs
        path: target/doc

  website:
    needs: [core, dom, fmt, clippy, docs]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: main

    - name: download dom examples
      uses: actions/download-artifact@master
      with:
        name: dom-examples
        path: main/dom/examples

    - name: download docs
      uses: actions/download-artifact@master
      with:
        name: docs
        path: main/target/doc

    - name: checkout gh-pages branch
      uses: actions/checkout@master
      with:
        ref: gh-pages
        path: website

    - name: clean website directory
      # https://stackoverflow.com/questions/22339837/linux-command-to-delete-all-files-except-git-folder
      run: |
        git rm -rf .
        git clean -fxd
      working-directory: website

    - name: build website
      run: cargo ofl website build ../website
      working-directory: main

    - name: push website to gh pages
      if: github.ref == 'refs/heads/master'
      run: |
        git add -a
        git commit -m $GITHUB_SHA
        git push origin gh-pages
      working-directory: website

  published:
    needs: [website]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: ensure all crates published
      if: github.ref == 'refs/heads/master'
      run: |
        cargo login ${{ secrets.CARGO_API_TOKEN }}
        cargo ofl published
