on: push
jobs:
  xplat:
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04, windows-2019]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@master

    - name: install rustup
      if: matrix.os == 'macOS-10.14'
      run: curl https://sh.rustup.rs -sSf | sh -s

    - name: deps
      run: |
        rustup component add rustfmt clippy
        rustup target add wasm32-unknown-unknown
        cargo install cargo-script

    - name: core
      run: cargo test-core

    - name: dom
      run: |
        cargo check-dom-lib
        cargo build-dom-hacking
        cargo build-dom-todo

    - name: formatting
      run: |
        cargo fmt -- --check
        cargo fmt-scripts --check

    - name: docs
      run: cargo docs-all

    - name: clippy
      run: |
        cargo clippy-core
        cargo clippy-dom
