on: push
jobs:
  xplat:
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04, windows-2019]
    
    steps:
    - uses: actions/checkout@master
    - name: deps
      run: |
        rustup component add rustfmt clippy
        rustup target add wasm32-unknown-unknown
        cargo install cargo-script
    - name: formatting
      run: |
        cargo fmt -- --check
        cargo fmt-scripts --check
    - name: core
      run: cargo test-core
    - name: docs
      run: cargo docs-all
    - name: dom
      run: |
        cargo check-dom-lib
        cargo build-dom-hacking
        cargo build-dom-todo
    - name: clippy
        cargo clippy-core
        cargo clippy-dom
