on: push
jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - run: cargo test-core

  dom:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo check-dom-lib
    - run: cargo build-dom-hacking
    - run: cargo build-dom-todo
    - uses: actions/upload-artifact@master
      with:
        name: dom-examples
        path: dom/examples

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add rustfmt
    - run: cargo fmt -- --check
    # FIXME https://github.com/anp/moxie/issues/27
    # - run: cargo fmt-tools -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rustup component add clippy
    - run: cargo clippy-core
    - run: cargo clippy-dom

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cargo docs-all
    - run: cargo docs-ofl
    - uses: actions/upload-artifact@master
      with:
        name: docs
        path: target/doc

  website:
    needs: [core, dom, fmt, clippy, docs]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: dom-examples
        path: dom/examples
    - uses: actions/download-artifact@master
      with:
        name: docs
        path: target/doc
    - run: cargo ofl website build target/website

  published:
    needs: [website]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - if: github.ref == 'ref/heads/master'
      run: |
        cargo login ${{ secrets.CARGO_API_TOKEN }}
        cargo ofl published
